from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def utc_timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def write_json(path: str | Path, data: Any) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2, sort_keys=False), encoding="utf-8")


def write_csv(path: str | Path, rows: list[dict[str, Any]], headers: list[str] | None = None) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    if headers is None:
        header_set: list[str] = []
        for row in rows:
            for key in row.keys():
                if key not in header_set:
                    header_set.append(key)
        headers = header_set
    with p.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_markdown(path: str | Path, report: dict[str, Any]) -> None:
    lines = [
        "# Okta API Access Audit Report",
        "",
        f"Generated: `{report.get('timestamp', '')}`",
        "",
        "## Summary",
        "",
        f"- API tokens exported: {report.get('apiTokens', 0)}",
        f"- OAuth apps selected: {report.get('oauthApps', 0)}",
        f"- App grants exported: {report.get('appGrants', 0)}",
        f"- Client role assignments exported: {report.get('clientRoles', 0)}",
        f"- Risk findings: {report.get('riskFindings', 0)}",
        f"- Request failures: {report.get('requestFailures', 0)}",
        "",
        "## Risk Finding Counts",
        "",
    ]
    finding_counts = report.get("findingCounts", {}) or {}
    if finding_counts:
        for severity, count in sorted(finding_counts.items()):
            lines.append(f"- {severity}: {count}")
    else:
        lines.append("- No findings generated by the configured rules.")
    lines.extend([
        "",
        "## Notes",
        "",
        "This report is generated from read-only Okta API calls. Review CSV and JSON evidence files before storing or sharing output from client environments.",
    ])
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
