from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def utc_timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def write_json(path: str | Path, data: Any) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2, sort_keys=False), encoding="utf-8")


def write_csv(path: str | Path, rows: list[dict[str, Any]], headers: list[str] | None = None) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    if headers is None:
        header_set: list[str] = []
        for row in rows:
            for key in row.keys():
                if key not in header_set:
                    header_set.append(key)
        headers = header_set
    with p.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def severity_counts(findings: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for finding in findings:
        severity = str(finding.get("severity", "INFO") or "INFO")
        counts[severity] = counts.get(severity, 0) + 1
    return counts


def write_markdown(path: str | Path, report: dict[str, Any]) -> None:
    lines = [
        "# Okta Rate Limit Monitor Report",
        "",
        f"Generated: `{report.get('timestamp', '')}`",
        "",
        "## Summary",
        "",
        f"- Header probes executed: {report.get('headerProbes', 0)}",
        f"- System Log rate-limit events found: {report.get('systemLogEvents', 0)}",
        f"- Planned operations estimated: {report.get('plannedOperations', 0)}",
        f"- Risk findings: {report.get('riskFindings', 0)}",
        f"- Request failures: {report.get('requestFailures', 0)}",
        "",
        "## Finding Counts",
        "",
    ]
    counts = report.get("findingCounts", {}) or {}
    if counts:
        for severity, count in sorted(counts.items()):
            lines.append(f"- {severity}: {count}")
    else:
        lines.append("- No findings generated by the configured rules.")
    lines.extend([
        "",
        "## Notes",
        "",
        "This report is generated from read-only Okta API calls and local planned operation estimates. Review CSV and JSON evidence files before running large backups, imports, migrations, Terraform runs, or other high-volume automations.",
    ])
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def create_output_dir(base_dir: str | Path, prefix: str = "rate-limit-monitor") -> Path:
    output_dir = Path(base_dir) / f"{prefix}-{utc_timestamp()}"
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir
